### ISSUE TITLE
Join slack!

### ISSUE THREAD

**Issue by ColinEberhardt** [01alchemist/TurboScript#142]
Hi, I’d be interested in joining the slack channel and potentially contributing. My email is colin (dot) Eberhardt (at) gmail (dot) com

**Comment by nidin** [comment]
Hi @ColinEberhardt,
Slack channel is not active. I don't have enough time to work on TurboScript due to my daily job.
But I am working on a language specification instead of implementing new features in this repo.
Anyway this repo was mainly for a prototype and it reached its goal.
Spec repo can be found here. https://github.com/TurboScriptLang/spec/blob/master/spec.md
If you are interested, you may contribute to standardize the language specification.

**Comment by ColinEberhardt** [comment]
That's a shame - but thanks for letting me know!
