### ISSUE TITLE
Setup jest test framework

### ISSUE THREAD

**Issue by nidin** [01alchemist/TurboScript#19]
**What?**
Setup karma or better test framework then add basic test suites.

**Comment by winksaville** [comment]
Is Alsatian good enough for now, maybe close.

**Comment by nidin** [comment]
I am having little trouble with Alsatian.
1. Decorators are not yet standardized
2. For me it's throwing errors. I'll share the details soon.
3. When compare with other tools like jest, It is lacking features.
3. Cannot test typescript directly
4. No builtin watch and continues testing

For an alternative I am experimenting with Jest from Facebook.

**Comment by winksaville** [comment]
What do you mean you can't test Typescript directly?

I can take a look at any problems, point me to them, I can look at them today.

**Comment by nidin** [comment]
Typescript need to compile to JavaScript manually to test with Alsatian.
With ts-jest we don't need to compile typescript manually

**Comment by winksaville** [comment]
Well, I'm not sure I want automatic compilation as I think (could be wrong) I need to be in control of the tsconfig.json, at least that's what I'm finding.

**Comment by nidin** [comment]
You can also pass tsconfig to Jest.

**Comment by winksaville** [comment]
Good.

I like the annotation technique, especially TestCase but if you find
ts-jest better, np. Do let me as see the problem you're having if you don't
come up with a solution.

**Comment by nidin** [comment]
I also like the concept of annotation (decorators) but Alsatian is not
working as I expected also the transpiled JavaScript code is bit heavy.

**Comment by winksaville** [comment]
Let me know what's not working.

**Comment by nidin** [comment]
I cannot reproduce the issue in Windows. It only shows in Mac. Could be an issue with tsc version. Right now I don't have mac to test it.

**Comment by nidin** [comment]
I wan to cleanup script section in package.json. I am thinking about something like this.
```json
{
  "scripts": {
    "build": "SCRIPT_TO_BUILD_COMPILER_AND_LIB",
    "watch-build": "SCRIPT_TO_WATCH_CHANGES_AND_RUN_ABOVE_BUILD",
    "test": "SCRIPT_TO_BUILD_COMPILER_AND_LIB_THEN_BUILD_TESTS_AND_RUN",
    "watch-test": "SCRIPT_TO_WATCH_CHANGES_AND_RUN_ABOVE_TEST",
    "publish": "SCRIPT_TO_PUBLISH_ONLY_COMPILER_TO_NPM"
  }
}
```
and I want to make scripts portable by avoiding platform dependent codes. it should work on Linux, Mac and Windows without a problem.

**some advantages of Jest**
Jest will watch file changes and only run related tests. Its easy for TDD.
http://facebook.github.io/jest/docs/cli.html#watch
We can configure tests inside package.json 
http://facebook.github.io/jest/docs/getting-started.html#using-typescript
With ts-jest, we don't need to compile typescript manually. It just compile ts on the fly. no need to worry about folder structure and output directory.
and more... 
I found it more easy to work with.

**Comment by winksaville** [comment]
I was thinking, changing to scripts and having them run on any platform is a good long term goal, but in the short term I wonder if we should focus on one platform for the compiler development and runtime. I'd vote for Linux for development and node-v8 for runtime.

As for testing jest/ts-jest is fine, but I know nothing, so @nidin could you please create an initial test since it sounds like you've already done some work?

**Comment by nidin** [comment]
I disagree on arrowing development down to node.js because. 
1. WebAssembly Implementation in Node.js is not yet completely ready.
2. All major browsers already support full WebAssembly v1
3. Primary target is browser since Node.js user can already use native code compiled from C++ or other languages.

I will setup Jest and add few tests both for node.js and browser

**Comment by winksaville** [comment]
OK, do you want both or just browser?

What is your opinion on the current development platforms, I'd suggested just Linux for short term?

**Comment by nidin** [comment]
wherever webassembly can run. 
I am working with all three platforms. Windows workstation mainly for graphics programming, Mac book pro for office and other normal works, Linux special cases; mainly for compatibility check and deployment setup. So I would keep all three platforms active during development.

**Comment by winksaville** [comment]
I agree all popular and capable systems need to be supported. I just
suggest all alpha work be done using 1 dev system and 1 target, it will
make less work during this time of greatest changes. To make changes to
support 3 dev systems and 2 or 3 targets we're potentially have 6 to 9
combinations to test and support, that seems like a lot. If we choose 1 dev
and 1 target there is only 1 combination to test and make initial changes
to. That means greater development velocity and in the long term a better
product because there will be less work to making major changes when
"necessary".

On the development side I'm pretty much Linux only, with 3 systems
available. I do have access to Windows and Mac but its less convenient.

Of course, as the captain its your decision :)

**Comment by nidin** [comment]
Of course our continues integration only test against node.js on Linux but I need to make sure it is working on at least chrome and Firefox.

**Comment by winksaville** [comment]
OK
