### ISSUE TITLE
I want to contribute, what knowledge do I need? Llvm?

### ISSUE THREAD

**Issue by liangzeng** [01alchemist/TurboScript#84]
I want to contribute, what knowledge do I need? Llvm?

**Comment by nidin** [comment]
Hi @liangzeng we have a slack team if you are interested i can add you to the team. of course we can also discuss in github. 

We are planning to integrate TurboScript with TypeScript compiler since typescript already done great job in type checking. we are investigating on how to integrate with typescript. 

No LLVM knowledge needed at this point but I am planning an LLVM IR backend for TurboScript there for it helps in future. Most probably LLVM wasm backend can take .wasm as input and output optimised wasm. if that is the case we don't even need LLVM IR for optimisation. 

If everything went well on typescript compiler integration we will mainly work on webassembly backend. TurboScript's primary goal is to align with JavaScript ES6 features. our primary targets will be WebAssembly and JavaScript (probably experimental C++). There will be no garbage collector in WebAssembly for now, this will be the main difference from JavaScript.

**Comment by nidin** [comment]
@liangzeng We have a new thread to discuss TypeScript compiler integration here #87 . Its seems not easy therefore we will keep the current compiler code base and make it more sound and bug free. If you have any crazy ideas please feel free to drop it here or create a new issue.
Looking forward to your contributions  💪

**Comment by liangzeng** [comment]
@nidin ok
